ej_goal_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

end

ej_goal_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ej_goal_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :bigint(8)        not null, primary key
#  name          :string           not null
#  password      :string           not null
#  session_token :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class User < ApplicationRecord
  validates :name, :session_token, :password_digest, presence: true
  validates :name, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}

  after_initialize :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.base64
  end

  def self.find_by_credentials(name, password)
    user = User.find_by(name: name)
    return nil unless user
    return user if user.is_password?(password)
    nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end



end

ej_goal_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def log_out!(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def log_in!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end

end

ej_goal_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(params[:user][:name], params[:user][:password])
    if user
      log_in!(user)
      render :new #dummy render. will switch later
    else
      flash.now[:errors] = ["invalid credentials"]
      render :new
    end
  end

  def destroy
    log_out!(current_user)
    render :new
  end

end

ej_goal_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in!(@user)
      render :new    #TODO we will change this later
    else
      flash[:errors] = ['invalid parameters']
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password)
  end
end

ej_goal_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ej_goal_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%if current_user %>
    <form action="<%=session_url%>" method="post">
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" name="" value="Log Out">
    </form>
    <p><%=current_user.name%></p>
    <% end %>
    <%= yield %>
  </body>
</html>

ej_goal_app/app/views/users/new.html.erb
<h1>New User</h1>

<form action="<%=users_url%>" method="post">
  <label>Name
    <input id='name' type="text" name="user[name]" value="">
  </label>
  <label>Password
    <input type="text" id='password' name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">

</form>